- name: catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: disable and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
  - name: install nodejs
    ansible.builtin.dnf:
     name: nodejs
     state: present

  - name: create user 
    ansible.builtin.user:
      name: roboshop

  - name: create directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download file 
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
     dest: /tmp